# generate-ms-defender-scout-report.ps1
$ErrorActionPreference = 'Stop'

# Input from environment
$clientId     = $env:AZURE_CLIENT_ID
$clientSecret = $env:AZURE_CLIENT_SECRET
$tenantId     = $env:AZURE_TENANT_ID

# Output file
$outputPath = "./ms-defender-scout-report.html"

# Load queries
$queries = Get-Content $env:QUERY_PATH | Where-Object { $_.Trim() -ne "" }

# Bootstrap HTML layout
$dateNow = Get-Date -Format "MMMM dd, yyyy"
$html = @"
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Microsoft Defender Scout Report</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background-color: #f8f9fa;
      margin: 0;
      padding: 0;
    }
    .container {
      max-width: 1200px;
      margin: auto;
      padding: 40px;
      background-color: #fff;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    header {
      border-bottom: 3px solid #00a4ef;
      padding-bottom: 10px;
      margin-bottom: 30px;
    }
    h1 { 
      color: #0078d4; 
      margin: 0;
    }
    h2 { 
      color: #00a4ef; 
      border-bottom: 2px solid #dee2e6; 
      padding-bottom: 6px; 
      margin-top: 30px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 15px;
      overflow-x: auto;
    }
    th, td {
      padding: 12px 15px;
      border: 1px solid #dee2e6;
      text-align: left;
      word-wrap: break-word;
    }
    th {
      background-color: #0078d4;
      color: white;
      font-weight: 600;
    }
    tr:nth-child(even) {
      background-color: #f8f9fa;
    }
    tr:hover {
      background-color: #e9ecef;
    }
    .status-ok { color: green; font-weight: bold; }
    .status-warning { color: orange; font-weight: bold; }
    .status-error { color: red; font-weight: bold; }
    .section { 
      margin-bottom: 40px; 
      padding: 20px;
      background-color: #ffffff;
      border-radius: 5px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    code {
      background-color: #f4f4f4;
      padding: 2px 6px;
      border-radius: 3px;
      font-family: 'Consolas', 'Monaco', monospace;
      font-size: 0.9em;
      display: block;
      margin: 10px 0;
      padding: 10px;
      overflow-x: auto;
    }
    footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 2px solid #dee2e6;
      font-size: 0.85em;
      color: #6c757d;
      text-align: center;
    }
    .metadata {
      color: #6c757d;
      font-size: 0.95em;
    }
  </style>
</head>
<body>
<div class="container">
<header>
  <h1>🛡️ Microsoft Defender Scout Assessment Report</h1>
  <p class="metadata"><strong>Date:</strong> $dateNow</p>
  <p class="metadata"><strong>Generated By:</strong> Microsoft Defender Scout</p>
  <p class="metadata"><strong>Tenant ID:</strong> $tenantId</p>
</header>
"@

function Get-AccessToken {
    Write-Host "🔐 Authenticating with Microsoft Graph API..." -ForegroundColor Cyan
    $body = @{
        client_id     = $clientId
        client_secret = $clientSecret
        scope         = "https://graph.microsoft.com/.default"
        grant_type    = "client_credentials"
    }
    $tokenUri = "https://login.microsoftonline.com/$tenantId/oauth2/v2.0/token"

    try {
        $response = Invoke-RestMethod -Method POST -Uri $tokenUri -Body $body -ContentType "application/x-www-form-urlencoded"
        Write-Host "✅ Authentication successful!" -ForegroundColor Green
        return $response.access_token
    } catch {
        Write-Host "❌ Authentication failed: $($_.Exception.Message)" -ForegroundColor Red
        throw
    }
}

function Run-AdvancedHuntingQuery {
    param (
        [string]$AccessToken,
        [string]$Query
    )
    
    $url = "https://graph.microsoft.com/v1.0/security/runHuntingQuery"
    $headers = @{
        "Authorization" = "Bearer $AccessToken"
        "Content-Type"  = "application/json"
    }
    
    $body = @{
        Query = $Query
    } | ConvertTo-Json -Depth 3
    
    try {
        $response = Invoke-RestMethod -Method Post -Uri $url -Headers $headers -Body $body
        return $response
    } catch {
        $errorMessage = $_.Exception.Message
        if ($_.ErrorDetails.Message) {
            try {
                $errorDetails = $_.ErrorDetails.Message | ConvertFrom-Json
                $errorMessage = $errorDetails.error.message
            } catch {
                $errorMessage = $_.ErrorDetails.Message
            }
        }
        return @{ error = $errorMessage }
    }
}

# Get token
$token = Get-AccessToken

# Run each query
$i = 1
foreach ($query in $queries) {
    Write-Host "`n🔍 Running Query $i..." -ForegroundColor Cyan
    Write-Host "$query" -ForegroundColor Gray
    
    $querytitle = $query.split('>>')[0].Trim()
    $querytext = $query.split('>>')[1].Trim()
    
    $html += "<div class='section'><h2>$querytitle</h2><p><code>$querytext</code></p>"

    $result = Run-AdvancedHuntingQuery -AccessToken $token -Query $querytext

    if ($result.error) {
        Write-Host "❌ Error: $($result.error)" -ForegroundColor Red
        $html += "<p class='status-error'>Error: $($result.error)</p></div>"
        $i++
        continue
    }

    # Microsoft Graph Advanced Hunting returns results in a different structure
    if (-not $result.results) {
        Write-Host "⚠️ No results returned." -ForegroundColor Yellow
        $html += "<p class='status-warning'>No results returned.</p></div>"
        $i++
        continue
    }

    $results = $result.results
    
    if ($results.Count -eq 0) {
        Write-Host "⚠️ Query returned 0 rows." -ForegroundColor Yellow
        $html += "<p class='status-warning'>Query returned 0 rows.</p></div>"
        $i++
        continue
    }

    Write-Host "✅ Query returned $($results.Count) rows" -ForegroundColor Green

    # Get column names from the first result object
    $columns = $results[0].PSObject.Properties.Name

    $html += "<table><thead><tr>"
    foreach ($col in $columns) {
        $html += "<th>$col</th>"
    }
    $html += "</tr></thead><tbody>"

    foreach ($row in $results) {
        $html += "<tr>"
        foreach ($col in $columns) {
            $cellValue = $row.$col
            if ($null -eq $cellValue) {
                $cellValue = ""
            }
            # Handle different data types
            if ($cellValue -is [DateTime]) {
                $cellValue = $cellValue.ToString("yyyy-MM-dd HH:mm:ss")
            } elseif ($cellValue -is [Array]) {
                $cellValue = $cellValue -join ", "
            }
            $html += "<td>$cellValue</td>"
        }
        $html += "</tr>"
    }

    $html += "</tbody></table></div>"
    $i++
}

# Close HTML
$html += @"
<footer>
  <p>© $(Get-Date -Format "yyyy") Microsoft Defender Scout</p>
  <p>This is an automated security assessment report generated using Microsoft Graph Advanced Hunting API.</p>
  <p>For more information, visit <a href="https://github.com/samikroy/ms-defender-scout">GitHub Repository</a></p>
</footer>
</div>
</body>
</html>
"@

# Save to file
$html | Set-Content -Path $outputPath -Encoding UTF8

Write-Host "`n✅ Report generated successfully: $outputPath" -ForegroundColor Green
Write-Host "📄 Open the HTML file in your browser to view the report." -ForegroundColor Cyan
